app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'auth'], function () {

    Route::get('/',function ()
    {
        return redirect()->route('project.index');
    });


    Route::get('/backup',['uses'=>'BackupController@backup','as'=>'db.backup']);
    Route::get('/restore',['uses'=>'BackupController@restore','as'=>'db.restore']);

    Route::resource('project', 'ProjectController');

    Route::get('project/history','ProjectController@history');



    Route::get('/check','FolderController@check');

    // Route::get('/project_test','ProjectController@test');

    Route::get('/project/{id}/history',['uses'=>'ProjectController@history','as'=>'project.history']);
    Route::get('/projectbackup/{id}/restore',['uses'=>'ProjectController@restore','as'=>'project.backup.restore']);
    Route::get('/projectbackup/{id}/backup',['uses'=>'ProjectController@takeBackup','as'=>'project.backup.now']);
    // Route::get('/project_schedule','ProjectController@scheduleDaily');

    // Route::get('/test', ['uses'=>'DbaseController@index','as'=>'check.db']);

    // Route::get('/checkftp','BackupController@ftpCheck');

    // Route::get('/cleanup','ProjectController@cleanup');

});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
	
    
    public function folders()
    {
        return $this->hasMany('App\Folder');
    }
   
    public function dbases()
    {
        return $this->hasMany('App\Dbase');
    }
    public function history()
    {
        return $this->hasMany('App\ProjectBackup');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ProjectCreateRequest;

use View;
use App\Http\Requests;
use App\Project;
use App\Folder;
use App\Dbase;

use App\ProjectBackup;
use Carbon\Carbon;
use DateTime;
use App\Backman;

use Log;
use File;
use FTP;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $projects = Project::with('folders','dbases')->orderBy('created_at', 'asc')->get()->toArray();

        foreach ($projects as $key=>$project) {
            $projects[$key]['folderNames'] = implode(', ', collect($project['folders'])->lists('name')->toArray());
            $projects[$key]['dbaseNames'] = implode(', ', collect($project['dbases'])->lists('name')->toArray());
        }
        // dd($projects);
        return view('projects.index', [
        'projects' => $projects]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projects.create');
    }
    public function test(Request $req)
    {
        dd('asdsa');
        

        return $data;


        // $dbase = new Dbase();
        // $dbase->name = new string();
        // $dbase->desc = new string();
        
        // $project->dbases()->save($dbase);

        


        // dd($dbase);

        // $p1 = Project::find(5);
        // dd($p1->dbases);

        // $db = Dbase::find(2);
        // dd($db->project);

        // $folder = new Folder();
        // $folder->name = new string();
        //  $folder->path = new string();
        //   $folder->desc = new string();

    }

    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectCreateRequest $request)
    {
        $data = $request->all();
        $project = new Project();
        $project->name = $data['Name'];
        $project->time_period = $data['repeat'];
        $project->time_picked = $data['timePicked'];
        $project->dayName = ucfirst($data ['dayName']);

        $project->cleanup = $data['cleanup'];


        if (isset($data['check_this'])){
            $project->ftp = true;
        }
        else{
            $project->ftp=false;
        }
        $project->date_of_Month = $data ['date'];

        if ($project->time_period=='daily') {
            $project->dayName=Null;
            $project->date_of_Month=Null;
        }
        if ($project->time_period=='weekly') {
            $project->date_of_Month=Null;
        }
        if ($project->time_period=='monthly') {            
            $project->dayName=Null;
        }

        $project->save();
        
        if (isset($data['folderName'])) {
            for ($i=0; $i < count($data['folderName']); $i++) { 
                $folder = new Folder();
                $folder->name = $data['folderName'][$i];
                $folder->path = $data['folderPath'][$i];
                $folder->desc = $data['folderDesc'][$i];
                $project->folders()->save($folder);
            }
        }
        if (isset($data['dbaseName'])) {
            for ($i=0; $i <count($data['dbaseName']) ; $i++) { 
                $dbase = new Dbase();
                $dbase->name = $data['dbaseName'][$i];
                
                $dbase->desc = $data['dbaseDesc'][$i];
                $project->dbases()->save($dbase);

            }
        }

        return redirect('/project');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return view('projects.history');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         
         $project = Project::find($id)->with('folders','dbases')->orderBy('created_at', 'asc')->first();
         $folderJson = json_encode($project->folders);
         return view('projects.edit', [
        'project' => $project,'folderJson'=>$folderJson]);

         
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
         $project = Project::findOrFail($id);

        $this->validate($request, [
        'name' => 'required',
        'time_period' => 'required',
        'time_picked'=>'required',
        'dayName'=>'required',
        'date_of_Month'=>'required'
        ]);

        for ($i=0; $i < count(['folderName']); $i++) { 
            $folder = Folder::findOrFail($id);
            $this->validate($request,[
                'name'=>'required',
                'path'=>'required',
                'desc'=>'required'

                ]);
            
            $project->folders()->save($folder);
        }
        for ($i=0; $i < count(['dbaseName']); $i++) { 
            $folder = Folder::findOrFail($id);
            $this->validate($request,[
                'name'=>'required',
                'path'=>'required',
                'desc'=>'required'

                ]);
            
            $project->dbases()->save($folder);
        }


        $input = $request->all();

        $project->fill($input)->save();

        Session::flash('flash_message', 'Project successfully added!');

        return redirect()->back();


    }

    public function history($id){
        $project = Project::where('id',$id)->with(['history','dbases','folders'])->first();
        return view('projects.history',['project'=>$project]);
    }


    public function restore($id)
    {
       $projectBackup = ProjectBackup::find($id);
       $project = $projectBackup->project;
       $backman = new Backman();
       $backman->populateFromProject($project);
       if ($projectBackup->ftp) {
           $backman->restoreBackup($projectBackup->path,'ftp');
       }else{
           $backman->restoreBackup($projectBackup->path,'local');
       }
       return redirect()->route('project.index');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        // dd($id);

        $project = Project::where('id','=',$id)->with('dbases','folders')->first();

        foreach ($project->dbases as $key => $value) {
            $value->delete();
        }

        foreach ($project->folders as $key => $value) {
            $value->delete();
        }

        $project->delete();
        return redirect('project');
        
    }

    // public function scheduleDaily()
    // {
    //    $current = Carbon::now();
    //    $current->second = 0;
    //    $project = Project::find(6);
    // //    $this->takeBackup($project);
    // }

    // public function takeBackup($project)
    // {

    //     $backman = new Backman();
    //     $backman->populateFromProject($project);
    //     // dd($backman);
    //     $path = $backman->createBackup();
    //     dd($path);
    // }



    // public function cleanup()
    // {
    //     $projects = Project::where('status','=','pending')->with('folders','dbases')->get();
    //     foreach ($projects as $project) {
    //         $backman = new Backman();
    //         $backman->setConfig(['local'=>true,'ftp'=>true]);
    //         $backman->populateFromProject($project);
    //         // dd($backman);
    //         dd($backman->cleanup());    
    //     }
        
       
    // }

    public function takeBackup($project_id)
    {
        $project = Project::where('id','=',$project_id)->with('folders','dbases')->first();
        $date = new DateTime();
        Log::info('Took Backup of project id '.$project->id.' at '.$date->format('Y-m-d H:i:s'));

        $backman = new Backman();
        $backman->populateFromProject($project);
        $path = $backman->createBackup();

        $projectBackup = new ProjectBackup();
        $projectBackup->project_id = $project->id;
        $projectBackup->path = $path['local'];
        $projectBackup->ftp = false;
        $projectBackup->save();

        if ($project->ftp) {
            $projectFtpBackup = new ProjectBackup();
            $projectFtpBackup->project_id = $project->id;
            $projectFtpBackup->path = $path['ftp'];
            $projectFtpBackup->ftp = true;
            $projectFtpBackup->save();
        }
        return redirect()->route('project.index');
    }

}

resources/views/projects/cleanup.blade.php
	<div class="col-md-12">
		<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Clean Up</h3>
            </div>
             <!--  <div class="box-body">
                <div class="form-group col-md-4">
                  <label for="exampleInputEmail1">Name</label>
                  <input type="text" class="form-control"  placeholder="Name">
                </div> -->
               <!--  <div class="form-group col-md-4">
                  <label for="schedule">Schedule</label>
                  <input type="time" name="schedule" class="form-control" id="schedule" placeholder="Schedule">
                </div> -->
				        <!-- <div class="form-group col-md-4">
                  <label for="cleanup">Clean Up</label>
                  <input type="time" name="cleanup" class="form-control" id="cleanup" placeholder="Cleanup">
                </div> -->

                <div class="form-group col-md-4">
                  <label for="sel1">Select type:</label>
                  <select name="cleanup" class="form-control" id="repeat">
                    <option name="daily" value="daily">Daily</option>
                    <option name="weekly" value="weekly">Weekly</option>
                    <option name="monthly" value="monthly">Monthly</option>
                  </select>
                </div>

                

                <!-- <div class="form-group col-md-4" id ="picker">
                  <label >Time picker:</label>

                  <div class="input-group bootstrap-timepicker timepicker">
                    <input id="timepicker1" type="text" class="form-control input-small">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                  </div>
                </div> -->

                

                <!-- <div class="form-group col-md-4" id ="day-picker">
                  <label for="sel1">Select list:</label>
                  <select class="form-control" id="repeat">
                    <option >Sunday</option>
                    <option >Monday</option>
                    <option >Tuesday</option>
                    <option >Wednesday</option>
                    <option >Thursday</option>
                    <option >Friday</option>
                    <option >Saturday</option>
                  </select>
                </div> -->

               

                <!--  <div class="form-group col-md-4" id ="date-picker">
                  <label for="sel1">Select list:</label>
                  <select class="form-control" id="repeat">
                    @for($i=1;$i<=30;$i++)
                      <option >{{$i}}</option>
                    @endfor
                  </select>
                </div> -->



              </div>
              <div align="left" class="box-footer"></div>
              

              <div class="col-md-4">
                <input type="submit" id="submitButton"  name="submitButton" value="Submit">
              </div>
    </div>
	</div>
  <div class="clearfix"></div>

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Project Create
@endsection

@section('contentheader_title')
  This is sample content
@endsection


@section('main-content')
 <form action="{{route('project.store')}}" id="formSubmit" method="post">
  {{ csrf_field() }}


	<div class="col-md-12">
		<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Create Project</h3>
            </div>

                <div class="box-body">
                  @if ($errors->has())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }}<br>        
            @endforeach
        </div>
        @endif
                  <div class="form-group col-md-4" >
                    <label for="exampleInputEmail1">Name</label>
                    <input name="Name" type="text" class="form-control"  placeholder="Name">
                  </div>
                 

                  <div class="form-group col-md-4">
                    <label for="sel1">Select Time-Period:</label>
                    <select name="repeat" class="form-control" id="repeat">
                      <option name="daily" value="daily">Daily</option>
                      <option name="weekly" value="weekly">Weekly</option>
                      <option name="monthly" value="monthly">Monthly</option>
                    </select>
                  </div>
             
                  <div class="form-group col-md-4" id ="picker">
                    <label >UTC Time picker:</label>

                    <div class="input-group bootstrap-timepicker timepicker">
                      <input name="timePicked" id="timepicker1" type="text" class="form-control input-small">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                    </div>
                  </div>

                  <div class="form-group col-md-4" id ="checkFtp">
                        <label>
                            <input type="checkbox" name="check_this" >FTP
                        </label>
                   </div>

                  

                  <div class="form-group col-md-4" id ="day-picker">
                    <label for="sel1">Select Day:</label>
                    <select name="dayName" class="form-control" id="repeat">
                      <option name="sunday" value="sunday"> Sunday</option>
                      <option name="monday" value="monday"> Monday</option>
                      <option name="tuesday" value="tuesday"> Tuesday</option>
                      <option name="wednesday" value="wednesday"> Wednesday</option>
                      <option name="thursday" value="thursday"> Thursday</option>
                      <option name="friday" value="friday"> Friday</option>
                      <option name="saturday" value="saturday"> Saturday</option>
                    </select>
                  </div>

                 

                   <div class="form-group col-md-4" id ="date-picker">
                    <label for="sel1">Select Date:</label>
                    <select name="date" class="form-control" id="repeat">
                      @for($i=1;$i<=30;$i++)
                        <option >{{$i}}</option>
                      @endfor
                    </select>
                  </div>



                </div>
                <div align="left" class="box-footer"></div>
                @include('projects.databases')
                @include('projects.folders')


      </div>
      @include('projects.cleanup')
      
      
      
  	</div>
  
  <div class="clearfix"></div>



</form>
@include('projects.modals.folder.create')
@include('projects.modals.folder.edit')
@include('projects.modals.dbase.create')
@include('projects.modals.dbase.edit')

@endsection




@push('js')
   <script src="{{asset('js/project/folder/create.js')}}" type="text/javascript"></script>
   

<!-- endpush -->

<!-- push(js') -->
<script src="{{asset('js/project/dbase/create.js')}}" type="text/javascript"></script>
<script src="{{asset('plugins/timepicker/bootstrap-timepicker.min.js')}}"></script>

<!-- <script src="{{asset('public/plugins/datepicker/bootstrap-datepicker.js')}}"></script> -->



<script type="text/javascript">

  $('#timepicker1').timepicker({
    showInputs: false
  });

  jQuery(document).ready(function($) {
    
    $('#day-picker').hide();
    $('#date-picker').hide();
  
    $('#repeat').change(function(event) {
      
      if($(this).val()==='daily'){
        $('#picker').show();
        $('#day-picker').hide();
        $('#date-picker').hide();

      }
      if($(this).val()==='weekly'){
        $('#day-picker').show();
        $('#picker').show();
        $('#date-picker').hide();

      }
      if($(this).val()==='monthly'){
        $('#day-picker').hide();
        $('#picker').show();
        $('#date-picker').show();

      }



    });
  $( "#formSubmit" ).submit(function( event ) {

      

    $.each(folder.items, function(i,param){
        $('<input />').attr('type', 'hidden')
            .attr('name', 'folderName[]')
            .attr('value', param.name)
            .appendTo('#formSubmit');

            $('<input />').attr('type', 'hidden')
            .attr('name', 'folderPath[]')
            .attr('value', param.path)
            .appendTo('#formSubmit');

            $('<input />').attr('type', 'hidden')
            .attr('name', 'folderDesc[]')
            .attr('value', param.desc)
            .appendTo('#formSubmit');
      });
    $.each(db.items, function(i,param){
        $('<input />').attr('type', 'hidden')
              .attr('name', 'dbaseName[]')
              .attr('value', param.name)
              .appendTo('#formSubmit');


              $('<input />').attr('type', 'hidden')
                .attr('name', 'dbaseDesc[]')
                .attr('value', param.desc)
                .appendTo('#formSubmit');
      });

     




     // debugger;
    // alert( "Handler for .submit() called." );
    // event.preventDefault();
  });




    // $('#repeat').click(function(event) {
    //   if($('#repeat').val()==='daily'){
    //     $('#picker').show();
    //     $('#day-picker').hide();
    //     $('#date-picker').hide();

    //   }
    //   if($('#repeat').val()==='weekly'){
    //     $('#day-picker').show();
    //     $('#date-picker').hide();
        
    //   }

    //   if($('#repeat').val()==='monthly'){
    //     $('#date-picker').show();

    //   }
    // });

    

  });
  
</script>
@endpush
@push('css')
<link rel="stylesheet" href="{{asset('plugins/timepicker/bootstrap-timepicker.min.css')}}">
@endpush

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('htmlheader_title')
	Project Create
@endsection

@section('contentheader_title')
  This is sample content
@endsection


@section('main-content')
 <form action="{{route('project.store')}}" id="formSubmit" method="post">



{{ Form::model($project, ['action'  => ['ProjectController@edit', $project->id], 'role'=> 'form']) }}
  {{ csrf_field() }}

	<div class="col-md-12">
		<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Project</h3>
            </div>

                <div class="box-body">
                  <div class="form-group col-md-4" >
                    <label for="exampleInputEmail1">Name</label>
                    <input name="Name" type="text" value="{{$project->name}}" class="form-control"  placeholder="Name">
                  </div>
                 

                  <div class="form-group col-md-4">
                    <label for="sel1">Select Time-Period:</label>
                    <select name="repeat" class="form-control" id="repeat">
                      <option name="daily" value="daily">Daily</option>
                      <option name="weekly" value="weekly">Weekly</option>
                      <option name="monthly" value="monthly">Monthly</option>
                    </select>
                  </div>

                  

                  <div class="form-group col-md-4" id ="picker">
                    <label >Time picker:</label>

                    <div class="input-group bootstrap-timepicker timepicker">
                      <input name="timePicked" id="timepicker1" type="text" class="form-control input-small">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                    </div>
                  </div>

                  

                  <div class="form-group col-md-4" id ="day-picker">
                    <label for="sel1">Select Day:</label>
                    <select name="dayName" class="form-control" id="repeat">
                      <option name="sunday" value="sunday"> Sunday</option>
                      <option name="monday" value="monday"> Monday</option>
                      <option name="tuesday" value="tuesday"> Tuesday</option>
                      <option name="wednesday" value="wednesday"> Wednesday</option>
                      <option name="thursday" value="thursday"> Thursday</option>
                      <option name="friday" value="friday"> Friday</option>
                      <option name="saturday" value="saturday"> Saturday</option>
                    </select>
                  </div>

                 

                   <div class="form-group col-md-4" id ="date-picker">
                    <label for="sel1">Select Date:</label>
                    <select name="date" class="form-control" id="repeat">
                      @for($i=1;$i<=30;$i++)
                        <option >{{$i}}</option>
                      @endfor
                    </select>
                  </div>



                </div>
                <div align="left" class="box-footer"></div>
                @include('projects.databases')
                @include('projects.folders')


      </div>
      @include('projects.editCleanup')
      
      
      
  	</div>
  
  <div class="clearfix"></div>



</form>
@include('projects.modals.folder.create')
@include('projects.modals.folder.edit')
@include('projects.modals.dbase.create')
@include('projects.modals.dbase.edit')

@endsection




@push('js')
   <script src="{{asset('js/project/folder/create.js')}}" type="text/javascript"></script>
<!-- endpush

<!-- push(js') -->
<script src="{{asset('js/project/dbase/create.js')}}" type="text/javascript"></script>
<script src="{{asset('plugins/timepicker/bootstrap-timepicker.min.js')}}"></script>

<!-- <script src="{{asset('public/plugins/datepicker/bootstrap-datepicker.js')}}"></script> -->



<script type="text/javascript">

  retrievedFolders = jQuery.parseJSON('{!! $folderJson !!}');

  $('#timepicker1').timepicker({
    showInputs: false
  });

  jQuery(document).ready(function($) {
    
    $('#day-picker').hide();
    $('#date-picker').hide();
  
    $('#repeat').change(function(event) {
      
      if($(this).val()==='daily'){
        $('#picker').show();
        $('#day-picker').hide();
        $('#date-picker').hide();

      }
      if($(this).val()==='weekly'){
        $('#day-picker').show();
        $('#picker').show();
        $('#date-picker').hide();

      }
      if($(this).val()==='monthly'){
        $('#day-picker').hide();
        $('#picker').show();
        $('#date-picker').show();

      }



    });
  $( "#formSubmit" ).submit(function( event ) {

      

    $.each(folder.items, function(i,param){
        $('<input />').attr('type', 'hidden')
            .attr('name', 'folderName[]')
            .attr('value', param.name)
            .appendTo('#formSubmit');

            $('<input />').attr('type', 'hidden')
            .attr('name', 'folderPath[]')
            .attr('value', param.path)
            .appendTo('#formSubmit');

            $('<input />').attr('type', 'hidden')
            .attr('name', 'folderDesc[]')
            .attr('value', param.desc)
            .appendTo('#formSubmit');
      });
    $.each(db.items, function(i,param){
        $('<input />').attr('type', 'hidden')
              .attr('name', 'dbaseName[]')
              .attr('value', param.name)
              .appendTo('#formSubmit');


              $('<input />').attr('type', 'hidden')
                .attr('name', 'dbaseDesc[]')
                .attr('value', param.desc)
                .appendTo('#formSubmit');
      });

     




     // debugger;
    // alert( "Handler for .submit() called." );
    // event.preventDefault();
  });




    // $('#repeat').click(function(event) {
    //   if($('#repeat').val()==='daily'){
    //     $('#picker').show();
    //     $('#day-picker').hide();
    //     $('#date-picker').hide();

    //   }
    //   if($('#repeat').val()==='weekly'){
    //     $('#day-picker').show();
    //     $('#date-picker').hide();
        
    //   }

    //   if($('#repeat').val()==='monthly'){
    //     $('#date-picker').show();

    //   }
    // });

    

  });
  
</script>
@endpush
@push('css')
<link rel="stylesheet" href="{{asset('plugins/timepicker/bootstrap-timepicker.min.css')}}">
@endpush

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('htmlheader_title')
  Project Index
@endsection

@section('contentheader_title')
  
@endsection


@section('main-content')

  <div class="col-md-12">
    <div class="box box-primary">
        
            <div class="box-header with-border">
              <div class="col-md-6 text-left">
                <h3 class="box-title">Projects</h3>
              </div>
              <div class="col-md-6 text-right">
                <a class="btn btn-primary btn-sm" href="{{route('project.create')}}">Create New</a>
              </div>

            </div>

                <div class="box-body">
                      @if (count($projects) > 0)
                          
                           <table class="table table-striped task-table">

                    
                        <thead>
                            <th>Project Name</th>
                            <th>Time_Period</th>
                            <th>Time_Picked</th>
                            
                            <th>Day</th>
                            <th>Date</th>

                            <th>Folders</th>
                            <th>Databases</th>
                            <th>Ftp</th>
                            <th>Cleanups</th>
                            <th>Action</th>
                            
                        </thead>

                    <tbody>
                        @foreach ($projects as $project)
                            <tr>
                                
                                <td class="table-text">
                                  <a href="{{route('project.history',$project['id'])}}"><div>{{ $project['name'] }}</div></a>
                                    
                                    
                                </td>
                                <td>
                                  <div>{{ $project['time_period'] }}</div>
                                </td>
                                <td>
                                  <div>{{ $project['time_picked'] }}</div>
                                </td>
                                <td>
                                  <div>{{ $project['dayName'] }}</div>
                                </td>
                                <td>
                                  <div>{{ $project['date_of_Month'] }}</div>
                                </td>
                                 <td>

                                    {{$project['folderNames']}}

                                </td>

                                <td>
                                    {{$project['dbaseNames']}}
                                </td>
                                <td>
                                  @if($project['ftp'])
                                    <span class="label label-success">Yes</span>
                                  @else 
                                    <span class="label label-primary">No</span>
                                  @endif
                                </td>
                                <td>{{ucfirst($project['cleanup'])}}</td>
                                <td>

                                  <!-- <div><i class="glyphicon glyphicon-trash" ></i>
                                  <i class="glyphicon glyphicon-edit" ></i></div> -->

                                      {!! Form::open(['route' => ['project.destroy', $project['id']], 'method' => 'delete']) !!}
                                        {{ Form::submit('Delete',['class'=>'btn btn-xs btn-danger']) }}
                                      {!! Form::close() !!}

                                      <a class="btn btn-primary btn-xs" href="{{route('project.backup.now',$project['id'])}}">Backup</a>

                                      {{-- {!! Form::open(['route' => ['project.edit', $project['id']], 'method' => 'get']) !!}
                                        {{ Form::submit('edit',['class'=>'btn btn-xs btn-primary']) }}
                                      {!! Form::close() !!} --}}


                                </td>
                                

                                
                            </tr>
                        @endforeach
                         </tbody>
                </table>
            
    @endif
    </div>
    </div>
    </div>
@endsection

@push('js')
<script type="text/javascript">

jQuery(document).ready(function($) {


});

</script>
@endpush
               